# Generated by Django 5.1.15 on 2026-02-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_newsletter_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='newsletter_campaign',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='newsletter_recipients',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='newsletter_subject',
        ),
    ]
